# Build settings
[build]
  base = "/opt/build/repo"
  command = "npm run build"
  commandOrigin = "config"
  publish = "/opt/build/repo/build"
  publishOrigin = "config"
  environment = ["CHROMIUM_PATH"]

# Redirects
[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
